version: '3.8'

services:
  backend:
    image: wardakhan0101/bookverse-backend:latest
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/BOOKVERSE
      - JWT_SECRET=d1c82b7a639ab0f97b9f198fa6a15f729a1591b2a0f49ff16db2ac2e7e02c967
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - bookverse-network

  frontend:
    image: wardakhan0101/bookverse-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - bookverse-network

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bookverse-network

volumes:
  mongodb_data:

networks:
  bookverse-network:
    driver: bridge
