version: '3.8'

services:
  jenkins-bookverse-backend:
    image: node:18
    container_name: jenkins-bookverse-backend
    ports:
      - "5001:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - MONGODB_URI=mongodb://jenkins-bookverse-mongodb:27017/bookverse
      - JWT_SECRET=d1c82b7a639ab0f97b9f198fa6a15f729a1591b2a0f49ff16db2ac2e7e02c967
      - PORT=5000
    depends_on:
      - jenkins-bookverse-mongodb
    networks:
      - jenkins-bookverse-network

  jenkins-bookverse-frontend:
    image: nginx:alpine
    container_name: jenkins-bookverse-frontend
    ports:
      - "3001:80"
    volumes:
      - ./client/Final/dist:/usr/share/nginx/html
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jenkins-bookverse-backend
    networks:
      - jenkins-bookverse-network

  jenkins-bookverse-mongodb:
    image: mongo:7
    container_name: jenkins-bookverse-mongodb
    ports:
      - "27018:27017"
    volumes:
      - jenkins_mongodb_data:/data/db
      - ./database:/tmp/db_files
    networks:
      - jenkins-bookverse-network

volumes:
  jenkins_mongodb_data:

networks:
  jenkins-bookverse-network:
    driver: bridge
